# Generated by Django 5.2.17 on 2026-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_entity_type_companyprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_url',
            field=models.URLField(default='www.company.com'),
        ),
    ]
