# Generated by Django 5.2.9 on 2026-01-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='companydocument',
            old_name='is_verified',
            new_name='never_expires',
        ),
        migrations.AddField(
            model_name='companydocument',
            name='recipient',
            field=models.CharField(default=None, help_text='Document recipient / authority name', max_length=255),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_documents', to='documents.documenttype'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['company', 'document_type'], name='documents_c_company_5e195a_idx'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['recipient'], name='documents_c_recipie_5abafa_idx'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['status'], name='documents_c_status_77a4e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='companydocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_type', 'recipient'), name='unique_company_document'),
        ),
    ]
