# Generated by Django 5.2.9 on 2026-01-06 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0002_rename_uploaded_at_companydocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='company_templates/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.companyprofile')),
            ],
        ),
        migrations.AddField(
            model_name='companydocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_documents', to='documents.documenttemplate'),
        ),
    ]
