# Generated by Django 6.0.2 on 2026-02-11 14:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttemplate_companydocument_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='file',
        ),
        migrations.AddField(
            model_name='companydocument',
            name='document_json',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_html',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_json',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydocument',
            name='qr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document', to='documents.qrrecord'),
        ),
    ]
