# Generated by Django 5.1.4

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_qrrecord_remove_companydocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

