# Generated by Django 5.2.11 on 2026-02-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_companydocument_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydocument',
            name='document_json',
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.companydocument')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'key'], name='documents_d_documen_d07a5b_idx')],
                'unique_together': {('document', 'key')},
            },
        ),
    ]
