# Generated by Django 6.0.2 on 2026-02-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_companydocument_document_json_documentfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_html',
            field=models.TextField(),
        ),
    ]
