# Generated by Django 5.2.12 on 2026-03-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0007_alter_documenttemplate_template_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='accounts.companyprofile'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('company', 'template_name')},
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('company', 'code')},
        ),
    ]
