# Generated by Django 5.2.12 on 2026-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documenttemplate_document_type_documenttype_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='document_canvas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
